version: '3'
services:
  backend:
    image: idockerapi
    container_name: camino-back
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sadmin/Work/mounts/export:/code/export
      - /home/sadmin/Work/mounts/weights:/code/weights
    ports:
      - "8002:80"
    networks:
      - camino-net