version: '3'
services:
  backend:
    image: idockerapi
    container_name: camino-back
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /home/sadmin/Work/dockerpipe:/code/api/docker/hostpipe
    ports:
    - "8002:80"